In [1]:
import numpy as np
from scipy import linalg

In [2]:
mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.array([[.5],[1]])

In [3]:
mat1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
mat1[0,1]

2

In [5]:
mat1[:,0]

array([1, 4])

In [6]:
mat1[0,0:2]

array([1, 2])

In [7]:
mat2

array([[0.5],
       [1. ]])

In [9]:
mat4 = mat1**2
mat4

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [10]:
mat4 = mat1*mat1
mat4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
mat13 = 2*mat1
mat13

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
mat1 + mat1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
mat1 + mat2 # not valid in LA, but array op in numpy

array([[1.5, 2.5, 3.5],
       [5. , 6. , 7. ]])

In [15]:
mat5 = mat1.dot(mat1)
mat5

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [16]:
mat5 = mat1.dot(mat1.T)
mat5

array([[14, 32],
       [32, 77]])

In [17]:
mat6 = mat1.T.dot(mat1)
mat6

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [18]:
# inverting a non-square matrix throws an error
mat3 = linalg.inv(mat1)

ValueError: expected square matrix