In [1]:
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create np arrays by converting lists
# vector
vec = np.array([1,2,3])
print(vec)

# we can create matrices by converting lists of lists
mat = np.array([[1,2,3],[4,5,6],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 3]
 [4 5 6]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [3 6 9]]


In [4]:
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
print('')
mat3 = np.ones((3,5))
print(mat3)
print('')
mat4 = np.eye(5)
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat, vec)
print(product)

[[1 2 3]
 [4 5 6]
 [1 8 9]]

[1 2 3]

[14 32 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[-0.16666667  0.33333333 -0.16666667]
 [-1.66666667  0.33333333  0.33333333]
 [ 1.5        -0.33333333 -0.16666667]]


In [10]:
vec7 = np.array(['blue', 'red', 'orange', 'purple', 'purple', 'orange', 'Red', 6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
rand_mat = np.random.rand(5,5)
print(rand_mat)
rand_mat2 = np.random.randn(10,5)
print('')
print(rand_mat2)

[[0.77265171 0.60747573 0.53556253 0.61206352 0.11150519]
 [0.93998709 0.06420884 0.46366609 0.04034026 0.29911152]
 [0.37139053 0.41939333 0.67472785 0.28135302 0.23433466]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]

[[ 0.33958841 -0.06601247 -1.13340416  0.743269   -1.30964004]
 [-0.37668969  0.29880201 -1.9713231  -1.01842541  0.98361468]
 [-2.10604481 -1.91299814 -0.25397909 -1.003978    0.91369992]
 [-0.06278561 -1.00646037 -0.42472023 -0.79225465 -1.25764093]
 [ 0.64125073 -0.93661352 -0.29281324  0.28673217  0.07376983]
 [ 0.06933179 -0.37129732  0.37680153  0.73910838 -0.67933488]
 [ 0.7110616   1.12340036  0.00436613 -1.51744729 -0.79544902]
 [-2.43873424 -1.43006841  0.82098575 -0.62478957 -0.75205833]
 [ 1.63176557 -1.58075099 -1.16782365  0.79536169  0.1657827 ]
 [-0.42510129 -0.71938191 -0.11986081  1.05077753  0.81167111]]


In [12]:
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4595551888131147
0.947045168975231


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.038440546362056294
1.6317655713050034


In [14]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.23160618  1.62024452  0.39051251 -1.23714799  3.35131007 -0.44571868
 -0.2710108  -1.87894188  0.33934487 -1.27916971  0.23060204  0.10232483
 -1.45051988  1.85261594 -0.20932746  0.92727494  1.08348497  0.26847031
 -1.58593974]
-0.271010799054689


In [15]:
print(rand_vec[4:9])

[ 3.35131007 -0.44571868 -0.2710108  -1.87894188  0.33934487]


In [16]:
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.23160618 -1.23714799 -0.2710108  -1.27916971 -1.45051988]


In [17]:
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.77265171 0.60747573 0.53556253 0.61206352 0.11150519]
 [0.93998709 0.06420884 0.46366609 0.04034026 0.29911152]
 [0.37139053 0.41939333 0.67472785 0.28135302 0.23433466]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]
0.4636660862499805
0.4636660862499805


In [18]:
print(rand_mat[0:2,1:3])

[[0.60747573 0.53556253]
 [0.06420884 0.46366609]]


In [19]:
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.23160618  1.62024452  0.39051251 -1.23714799  3.35131007 -0.44571868
 -0.2710108  -1.87894188  0.33934487 -1.27916971  0.23060204  0.10232483
 -1.45051988  1.85261594 -0.20932746  0.92727494  1.08348497  0.26847031
 -1.58593974]

[ 1.23160618  1.62024452  0.39051251  4.          4.         -0.44571868
 -0.2710108  -1.87894188  0.33934487 -1.27916971  0.23060204  0.10232483
 -1.45051988  1.85261594 -0.20932746  0.92727494  1.08348497  0.26847031
 -1.58593974]

[ 1.23160618  1.62024452  0.39051251  1.          2.         -0.44571868
 -0.2710108  -1.87894188  0.33934487 -1.27916971  0.23060204  0.10232483
 -1.45051988  1.85261594 -0.20932746  0.92727494  1.08348497  0.26847031
 -1.58593974]


In [20]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.77265171 0.60747573 0.53556253 0.61206352 0.11150519]
 [0.93998709 0.06420884 0.46366609 0.04034026 0.29911152]
 [0.37139053 0.41939333 0.67472785 0.28135302 0.23433466]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]

[[0.77265171 0.60747573 0.53556253 0.61206352 0.11150519]
 [0.93998709 0.06420884 0.46366609 0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]


In [21]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.77265171 0.60747573 0.53556253]
 [0.93998709 0.06420884 0.46366609]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [22]:
print(rand_mat)

[[3.         3.         3.         0.61206352 0.11150519]
 [3.         3.         3.         0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]


In [23]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.61206352 0.11150519]
 [3.         3.         3.         0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]


In [24]:
rand_vec = np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.28642317 -0.6921171  -0.2522126   0.23260288  0.91931803  0.35747647
  0.03687399 -0.45785713 -1.49603119 -0.53905805 -0.6341214  -0.74716529
 -0.72707068  0.5389661   1.20660198]
[False False False  True  True  True  True False False False False False
 False  True  True]
[0.23260288 0.91931803 0.35747647 0.03687399 0.5389661  1.20660198]


In [25]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.33958841 -0.06601247 -1.13340416  0.743269   -1.30964004]
 [-0.37668969  0.29880201 -1.9713231  -1.01842541  0.98361468]
 [-2.10604481 -1.91299814 -0.25397909 -1.003978    0.91369992]
 [-0.06278561 -1.00646037 -0.42472023 -0.79225465 -1.25764093]
 [ 0.64125073 -0.93661352 -0.29281324  0.28673217  0.07376983]
 [ 0.06933179 -0.37129732  0.37680153  0.73910838 -0.67933488]
 [ 0.7110616   1.12340036  0.00436613 -1.51744729 -0.79544902]
 [-2.43873424 -1.43006841  0.82098575 -0.62478957 -0.75205833]
 [ 1.63176557 -1.58075099 -1.16782365  0.79536169  0.1657827 ]
 [-0.42510129 -0.71938191 -0.11986081  1.05077753  0.81167111]]
[0.33958841 0.743269   0.29880201 0.98361468 0.91369992 0.64125073
 0.28673217 0.07376983 0.06933179 0.37680153 0.73910838 0.7110616
 1.12340036 0.00436613 0.82098575 1.63176557 0.79536169 0.1657827
 1.05077753 0.81167111]


In [26]:
print(rand_vec)
print('')
rand_vec[rand_vec>.5] = -5
print(rand_vec)

[-0.28642317 -0.6921171  -0.2522126   0.23260288  0.91931803  0.35747647
  0.03687399 -0.45785713 -1.49603119 -0.53905805 -0.6341214  -0.74716529
 -0.72707068  0.5389661   1.20660198]

[-0.28642317 -0.6921171  -0.2522126   0.23260288 -5.          0.35747647
  0.03687399 -0.45785713 -1.49603119 -0.53905805 -0.6341214  -0.74716529
 -0.72707068 -5.         -5.        ]


In [27]:
np.save('saved_file_name', rand_mat2)

In [28]:
np.savez('zipped_filed_name', rand_mat=rand_mat, rand_mat2=rand_mat2)

In [31]:
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_filed_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.33958841 -0.06601247 -1.13340416  0.743269   -1.30964004]
 [-0.37668969  0.29880201 -1.9713231  -1.01842541  0.98361468]
 [-2.10604481 -1.91299814 -0.25397909 -1.003978    0.91369992]
 [-0.06278561 -1.00646037 -0.42472023 -0.79225465 -1.25764093]
 [ 0.64125073 -0.93661352 -0.29281324  0.28673217  0.07376983]
 [ 0.06933179 -0.37129732  0.37680153  0.73910838 -0.67933488]
 [ 0.7110616   1.12340036  0.00436613 -1.51744729 -0.79544902]
 [-2.43873424 -1.43006841  0.82098575 -0.62478957 -0.75205833]
 [ 1.63176557 -1.58075099 -1.16782365  0.79536169  0.1657827 ]
 [-0.42510129 -0.71938191 -0.11986081  1.05077753  0.81167111]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

[[3.         3.         3.         0.61206352 0.11150519]
 [3.         3.         3.         0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]

[[ 0.33958841 -0.06601247 -1.13340416  0.743269   -1.30964004]
 [-0.37668969  0.29880201 -1.9713231  -1.01842541  0.98361468]
 [-2.10604481 -1.91299814 -0.25397909 -1.003978    0.91369992]
 [-0.06278561 -1.00646037 -0.42472023 -0.79225465 -1.25764093]
 [ 0.64125073 -0.93661352 -0.29281324  0.28673217  0.07376983]
 [ 0.06933179 -0.37129732  0.37680153  0.73910838 -0.67933488]
 [ 0.7110616   1.12340036  0.00436613 -1.51744729 -0.79544902]
 [-2.43873424 -1.43006841  0.82098575 -0.62478957 -0.75205833]
 [ 1.63176557 -1.58075099 -1.16782365  0.79536169  0.1657827 ]
 [-0.42510129 -0.71938191 -0.11986081  1.05077753  0.81167111]]


In [34]:
np.savetxt('text_file_name.txt', rand_mat, delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt', delimiter=',')

print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.61206352 0.11150519]
 [3.         3.         3.         0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]

[[3.         3.         3.         0.61206352 0.11150519]
 [3.         3.         3.         0.         0.        ]
 [0.37139053 0.41939333 0.67472785 0.         0.        ]
 [0.60963644 0.7802665  0.26235452 0.58970555 0.21296957]
 [0.70029155 0.58594458 0.03844055 0.98229598 0.29920263]]
